### ISSUE TITLE
The exact Name `m_...` is not in scope

### ISSUE THREAD

**Issue by phadej** [haskell-compat/deriving-compat#19]
with deriving-compat-0.5

```
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE TemplateHaskell #-}

import Data.Deriving.Via
import Data.Monoid (Sum (..))

class Render a where
    render :: Monad m => a -> m String

instance Render Int where
    render = return . show

newtype MyInt = MkMyInt Int

$(deriveGND [t| Render MyInt |])
```

errors with

```
deriving-via.hs:15:3: error:
    The exact Name ‘m_a6gL’ is not in scope
      Probable cause: you used a unique Template Haskell name (NameU), 
      perhaps via newName, but did not bind it
      If that's it, then -ddump-splices might be useful
   |
15 | $(deriveGND [t| Render MyInt |])
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I tried with GHC-8.2.2 and GHC-8.4.3, neither work.

**Comment by RyanGlScott** [comment]
The error message is convoluted, but there is indeed a problem with your code. If you look at the code which is generated, you'll see:

```
[1 of 1] Compiling Main             ( Bug2.hs, interpreted )
Bug2.hs:17:3-31: Splicing declarations
    deriveGND [t| Render MyInt |]
  ======>
    instance Render MyInt where
      render ::
        forall (m :: GHC.Types.Type -> GHC.Types.Type).
        Monad m => MyInt -> m String
      render
        = (GHC.Prim.coerce @Int -> m String @MyInt -> m String) render
```

You'll see that `m` is bound by the method's type signature, so in order for it to correctly scope over the method type signature, you'll need to enable `ScopedTypeVariables`. This was not required in the previous version of `deriving-compat` since we were using impredicative instantiation, and thus didn't need to worry about type variable scoping.

Unfortunately, I don't see a better way to do this at the moment besides simply stating in the documentation that enabling `ScopedTypeVariables` is required here. The documentation currently does not say this, so I'll keep this ticket open as a reminder to fix this.

(Tangent: that `-ddump-splices` output revealed a [GHC pretty-printing bug](https://ghc.haskell.org/trac/ghc/ticket/15331).)

**Comment by RyanGlScott** [comment]
Actually, it turns out [we _already_ advertise the fact](https://github.com/haskell-compat/deriving-compat/blob/e95db6a5808665b096a0b6105c778a9de7a55227/src/Data/Deriving/Via.hs#L53) that `deriveGND` and `deriveVia` requires `ScopedTypeVariables`, so nothing needs to be done documentation-wise.

**Comment by phadej** [comment]
@RyanGlScott thanks!

**Comment by phadej** [comment]
... Changelog mentioned only InstanceSigs...

**Comment by RyanGlScott** [comment]
Ack, good catch. I've amended the changelog retroactively in 38ece26a9c7d45ad30a742b67e0e5349747466bb.

Do you think it's worth a minor Hackage release for this? It's a bit strange to make a release only for changelog purposes, but I'll do it if you'd find it valuable.

**Comment by phadej** [comment]
I wouldn't spam Hackage. It would be nice to be able to re-upload only Changelog / Readme.md as we can upload docs. Do you mind opening a ticket (if there aren't already) for hackage-server?

**Comment by RyanGlScott** [comment]
See https://github.com/haskell/hackage-server/issues/771.

**Comment by phadej** [comment]
Thanks!
